### PR TITLE
PROJECT: TESTING YOUR RUBY CODE

### PR DESCRIPTION
**Pull request by Elijahscriptdev**
Testing-enumerables
This is a project meant to test the methods written for the Enumerable Methods Project

### CODE REVIEW

**Comment by KaushikShivam** [comment]
# Project under review by shivam kaushik

**Review by KaushikShivam — CHANGES_REQUESTED** [review]
## Status: Changes required 🔴 

Hello @Elijahscriptdev 
Hope you're doing well. Good job on submitted the pull request.

However, I will have to mark your pull request as invalid for the following reasons:
- The pull request should have a descriptive README
- Pull Request should have a meaningful title and a short description

Please refer to the screenshot below
descriptive_readme

### Refer to this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) to make the necessary changes and request a pull request again.

Best,
Shivam

**Comment by shshamim63** [comment]
## Status :ambulance: [!! Invalid !!]
___
Hi @Elijahscriptdev  :wave: .
I am really sorry to mark this PR as invalid :disappointed:  cause, you were suppose to follow gitflow. but the created PR is asking to merge into master branch. And I am sorry that it was not informed previously.
image
___
#### Please fix this issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](@Shakhawat)

**Comment by shshamim63** [comment]
## Status :green_apple: !! Approved !! :green_apple: 
___
Hi @Elijahscriptdev :wave: ,
Well done :clap: ,
You have done a great job. You have fixed all the issues that have been mentioned above. The test cases also passes and covers most of the possible cases. :clap: 
___
### This :+1:  is from me, you can merge it. And don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Pull request merged**
